# Server settings
server:
  port: 8008
  # Enabling response compression to get a better performance for responses from service APIs
  compression:
    enabled: true
    min-response-size: 512
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json

# log4j setting  - Use this without logback.xml
#log4j:
#  rootUTCLogger: info

# logging configuration for Hibernate  - Use this without logback.xml
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: off #debug
#        type:
#          descriptor:
#            sql: off #trace

# Spring configuration
spring:
  # Service or application name
  application:
    name: concierge-api-gateway

  # Setting to create a distributed trace id for calls between services
  sleuth:
    sampler:
      probability: 1.0

  # Configuring routes
  cloud:
    gateway:
      routes:
        - id: cda-get-account-details
          #uri: http://localhost:8080
          uri: lb://concierge-debit-accounts
          predicates:
            - Path=/api/v1/accounts/**
            - Method=GET
          filters:
            - RewritePath=/api/v1/accounts/(?<segment>.*), /api/v1/accounts/$\{segment}
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: cda-account-reactivate
          #uri: http://localhost:8080
          uri: lb://concierge-debit-accounts
          predicates:
            - Path=/api/v1/accounts/{accountId}/reactivate
            - Method=PATCH
          filters:
            #- RewritePath=/api/v1/accounts/(?<segment>.*)/reactivate, /api/v1/accounts/$\{segment}/reactivate
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: cda-get-account-movements
          #uri: http://localhost:8080
          uri: lb://concierge-debit-accounts
          predicates:
            - Path=/api/v1/accounts/{accountId}/movements
            - Method=GET
          filters:
            #- RewritePath=/api/v1/accounts/(?<segment>.*)/movements, /api/v1/accounts/$\{segment}/movements
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: cda-add-movement
          #uri: http://localhost:8080
          uri: lb://concierge-debit-accounts
          predicates:
            - Path=/api/v1/accounts/{accountId}/movements
            - Method=POST
          filters:
            #- RewritePath=/api/v1/accounts/(?<segment>.*)/movements, /api/v1/accounts/$\{segment}/movements
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: cum-validate-account-owner
          #uri: http://localhost:8080
          uri: lb://concierge-user-management
          predicates:
            - Path=/api/v1/users/{userId}/accounts/{accountId}/validate
            - Method=GET
          filters:
            #- RewritePath=/api/v1/accounts/(?<segment>.*)/movements, /api/v1/accounts/$\{segment}/movements
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

      discovery:
        locator:
          lower-case-service-id: true

# Custom setting for the app
app:

  info:
    website: https://ngineapps.com
    name: @project.artifactId@
    version: @project.version@

eureka:
  client:
    serviceUrl:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8018/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    #mvn spring-boot:run -Dspring-boot.run.arguments=--instanceId=john
